style(script): Adjust indentation in TiDB health check script
- Standardize indentation from spaces to tabs for consistency.

Signed-off-by: tenfyzhong <tenfy@tenfy.cn>

diff --git a/tests/integration_tests/_utils/check_tidb_health b/tests/integration_tests/_utils/check_tidb_health
--- a/tests/integration_tests/_utils/check_tidb_health
+++ b/tests/integration_tests/_utils/check_tidb_health
@@ -20,13 +20,13 @@ while ! mysql -uroot -h "$host" -P "$port" --default-character-set utf8mb4 -e 's
 done
 
 if [ "$other_port" != "" ]; then
-    i=0
-    while ! mysql -uroot -h "$host" -P "$other_port" --default-character-set utf8mb4 -e 'select * from mysql.tidb;'; do
-        i=$((i + 1))
-        if [ "$i" -gt "$check_count" ]; then
-            echo 'Failed to start TiDB'
-            exit 2
-        fi
-        sleep 2
-    done
+	i=0
+	while ! mysql -uroot -h "$host" -P "$other_port" --default-character-set utf8mb4 -e 'select * from mysql.tidb;'; do
+		i=$((i + 1))
+		if [ "$i" -gt "$check_count" ]; then
+			echo 'Failed to start TiDB'
+			exit 2
+		fi
+		sleep 2
+	done
 fi
