style(scripts): Standardize indentation in shell scripts
- Changed indentation from 4 spaces to 1 tab character for consistency.

Signed-off-by: tenfyzhong <tenfy@tenfy.cn>

diff --git a/tests/integration_tests/_utils/check_changefeed_status b/tests/integration_tests/_utils/check_changefeed_status
--- a/tests/integration_tests/_utils/check_changefeed_status
+++ b/tests/integration_tests/_utils/check_changefeed_status
@@ -19,26 +19,26 @@ echo "$info"
 
 state=$(echo $info | jq -r '.state')
 if [[ ! "$state" == "$expected_state" ]]; then
-    echo "changefeed state $state does not equal to $expected_state"
-    exit 1
+	echo "changefeed state $state does not equal to $expected_state"
+	exit 1
 fi
 
 if [[ -z $field ]]; then
-    error_msg=$(echo $info | jq -r ".last_error")
-    if [[ ! $error_msg == "null" ]]; then
-        echo "last_error should be empty as expected"
-        exit 1
-    fi
-    error_msg=$(echo $info | jq -r ".last_warning")
-    if [[ ! $error_msg == "null" ]]; then
-        echo "last_warning should be empty as expected"
-        exit 1
-    fi
-    exit 0
+	error_msg=$(echo $info | jq -r ".last_error")
+	if [[ ! $error_msg == "null" ]]; then
+		echo "last_error should be empty as expected"
+		exit 1
+	fi
+	error_msg=$(echo $info | jq -r ".last_warning")
+	if [[ ! $error_msg == "null" ]]; then
+		echo "last_warning should be empty as expected"
+		exit 1
+	fi
+	exit 0
 fi
 
 error_msg=$(echo $info | jq -r ".$field.message")
 if [[ ! "$error_msg" =~ "$error_pattern" ]]; then
-    echo "error message '$error_msg' is not as expected '$error_pattern'"
-    exit 1
+	echo "error message '$error_msg' is not as expected '$error_pattern'"
+	exit 1
 fi
