update

diff --git a/tests/integration_tests/_utils/run_cdc_cli b/tests/integration_tests/_utils/run_cdc_cli
--- a/tests/integration_tests/_utils/run_cdc_cli
+++ b/tests/integration_tests/_utils/run_cdc_cli
@@ -13,8 +13,19 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-set -eux
+set -ux
 
 cdc.test -test.coverprofile="$OUT_DIR/cov.$TEST_NAME.cli.$$.out" cli "$@"
+    
+retry_times=0
+retry_max_times=5
+while [ $? -ne 0 ]; do
+    retry_times=$((retry_times+1))
+    if [ $retry_times -gt $retry_max_times ]; then
+        echo "Failed to run cdc cli"
+        exit 1
+    fi
+    cdc.test -test.coverprofile="$OUT_DIR/cov.$TEST_NAME.cli.$$.out" cli "$@"    
+done
 
 set +x
